language: node_js
node_js:
  - "9"

before_install:
  - npm install gulp -g

script:
  - npm install

cache:
  directories:
  - node_modules

notifications:
  email:
    - hryhorii.chaikovskyi@gmail.com
